export const SUPPORTED_RULES = new Set([
  'borderRadius',
  ...['', 'Top', 'Bottom', 'Right', 'Left'].flatMap(corner => [
    `border${corner}`,
    `border${corner}Color`,
    `border${corner}Width`,
    `border${corner}Style`,
  ]),
  'boxShadow',
  'flex',
  'alignSelf',
  'textAlign',
  'lineHeight',
  'fontSize',
  'fontWeight',
  'fontStyle',
  'letterSpacing',
  'cursor',
  'display',
  'height',
  'minHeight',
  'maxHeight',
  'width',
  'minWidth',
  'maxWidth',
  'position',
  'top',
  'bottom',
  'left',
  'right',
  'zIndex',
  'opacity',
  'transform',
  'color',
  'backgroundColor',
  'textTransform',
  'textDecoration',
  'textDecorationColor',
  'm',
  'mt',
  'mb',
  'ml',
  'mr',
  'mx',
  'my',
  'p',
  'py',
  'px',
  'pt',
  'pb',
  'pl',
  'pr',

  'flexDirection',
  'flexFlow',
  'flexWrap',
  'justifyContent',
  'flexBasis',
  'alignItems',
]);

export const PRAGMA_VALUE = 'jsx';
export const UI_KIT_SOURCE_NAME = '@stoplight/ui-kit';
export const EMOTION_SOURCE_NAME = '@emotion/core';
